### ISSUE TITLE
QHD：新档案问题汇总

### ISSUE THREAD

**Issue by marchtian** [steedos/records#121]
### 3月26日现场讨论涉及改进问题

- [ ] 归并入标准分支  https://github.com/steedos/creator/issues/1120 https://github.com/steedos/records/issues/113
- [x] 保管期限自动鉴定功能未能体现  https://github.com/steedos/records/issues/112
- [ ] 文书简化，年度改为数值型  https://github.com/steedos/records/issues/116
- [x] 搜索时，每一项改为一行显示https://github.com/steedos/records/issues/117
- [x] 在查找后，条目显示为0条，点“待接收”或“全部”仍显示0条，即之前查找的结果，只能再点“文书简化”才能显示条目。【新版已好，待升级后确认是否已好】https://github.com/steedos/creator/issues/708
- [x] 执行“编号调整”后，需自动刷新   https://github.com/steedos/records/issues/118
- [ ] 通过自定义视图来实现基于多个字段的排序  https://github.com/steedos/records/issues/119
- [ ] 在OA客户端上，原文、附件、表单等需直接打开  https://github.com/steedos/records/issues/120
- [x] 归档后的html文件只需发文单，无需附件和历史步骤 https://github.com/steedos/apps/issues/1989
