### ISSUE TITLE
【周安排】7/29-8/5

### ISSUE THREAD

**Issue by zonglu666** [steedos/records#90]
apps-申能

- [ ] [申能：开发webhook接口，用于处理分发之后的申请单数据汇总到源申请单](https://github.com/steedos/apps/issues/1838)

- [ ] [申能：分发出去的申请单处理结束时，应该给分发发起人发送推送消息，settings加开关](https://github.com/steedos/apps/issues/1839)

creator-档案系统

- [ ] [一阶段需完成的历史数据导入](https://github.com/steedos/records/issues/85)

- [ ] [相关验收文档](https://github.com/steedos/records/issues/86)

- [ ] [配置档案系统，数据初始化：借阅单、保管期限规则、保管期限、分类...](https://github.com/steedos/records/issues/89)
